version: "3"
services:
  app:
    image: node:20
    restart: always
    environment:
      - DEBUG=app:*
    env_file: ./.env
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      bash -c "sh init.sh && npm start"
